# Generated by Django 4.2.1 on 2023-10-17 01:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("visitor", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exit",
            name="id",
            field=models.BigAutoField(
                help_text="Exit ID", primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="exit",
            name="visitor",
            field=models.ForeignKey(
                db_column="visitor_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="visitor_exit",
                to="visitor.visitor",
            ),
        ),
    ]
