# Generated by Django 4.2.1 on 2023-10-17 02:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("visitor", "0005_alter_exit_id_alter_exit_visitor_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="exit",
            old_name="visitor_id",
            new_name="exit_id",
        ),
        migrations.AlterField(
            model_name="exit",
            name="id",
            field=models.BigAutoField(
                help_text="Exit ID", primary_key=True, serialize=False
            ),
        ),
    ]
