# Generated by Django 4.2.1 on 2023-10-17 02:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("visitor", "0006_rename_visitor_id_exit_exit_id_alter_exit_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="exit",
            old_name="exit_id",
            new_name="visitor_id",
        ),
    ]
