# Generated by Django 4.2.1 on 2023-10-19 05:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("visitor", "0007_rename_exit_id_exit_visitor_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exit",
            name="visitor_id",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="visitor",
            name="id",
            field=models.BigAutoField(
                help_text="Visitor ID", primary_key=True, serialize=False
            ),
        ),
    ]
