# Generated by Django 4.2.1 on 2023-10-19 05:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("visitor", "0008_alter_exit_visitor_id_alter_visitor_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="visitor",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
